# Default values for helm-argo-rollouts deployment

# Version of the configuration package to install
version: latest

# Skip dependency resolution - set to true if functions are managed separately
skipDependencyResolution: false
